package exceptionCustom;

public class ExceptionTest2 {

	public static void main(String[] args) throws InterruptedException {

		int num=10;
		int div=0;
		
		Thread.sleep(1000);
		
		div=num/2;
		System.out.println(div);
		
		
		



	}

}
